let arr1 = new Array();
arr1.push(56);
//arr1.push("ffgg");
let arr2 = new Array();
arr2.push(67);
arr2.push("hi");
console.log(arr2);
let arr3 = new Array();
arr3.push(78.9);
arr3.push(78);
arr3.push(78.93);
arr3.push(78);
//arr3.push(true);
arr3.push(new Number(34));
console.log(arr3);
let arr4 = new Array();
arr4.push("hi");
arr4.push("hi");
arr4.push("hello", "welcome");
//arr4.push(false);
arr4.push(new String("hello"));
console.log(arr4);
class Book {
    constructor(id = 0, name = "AA", price = 0) {
        this.id = id;
        this.name = name;
        this.price = price;
    }
}
let book1 = new Book(123, "Java Learning", 800);
let book2 = new Book(124, "Java Learning", 800);
let book3 = new Book(125, "Java Learning", 800);
let book4 = new Book(123, "Java Learning", 800);
let bookArray = new Array();
bookArray.push(book1);
bookArray.push(book2);
bookArray.push(book3);
bookArray.push(book4);
//bookArray.push("ghhjj");
bookArray.forEach(book => console.log(book));
let set1 = new Set();
set1.add(78.9);
set1.add(78);
set1.add(78.93);
set1.add(78);
console.log(set1);
let bookSet = new Set();
bookSet.add(book1);
bookSet.add(book2);
bookSet.add(book3);
bookSet.add(book4);
bookSet.forEach(book => console.log(book));
